dataset_path: /content/drive/MyDrive/pose_prediction_project/dataset/
save_path: /content/drive/MyDrive/pose_prediction_project/outputs/
log_path: /content/drive/MyDrive/pose_prediction_project/outputs/logs/
batch_size: 8
learning_rate: 0.001
num_epochs: 100